name: SnakeGame
on:
  workflow_dispatch:
jobs:
  pyinstaller-build:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: "3.12"
          spec: "snake.spec"
          #requirements: 'src/requirements.txt'
          upload_exe_with_name: "SnakeGame"
          options: --onefile, --name "My App", --windowed,
